### ISSUE TITLE
SMART Genomics APO

### ISSUE THREAD

**Issue by ychen306** [dcarbone/smart-precision-cancer-medicine#1]
What part of SMART Genomics API are you using?

**Comment by dcarbone** [comment]
At the time, we were using an extension of this resource: https://smartgenomics.wikispaces.com/GeneticObservation.

This allowed us to get Gene, Animo Acid, and Nucleotide information in a functional way as, at the time, the "appropriate" way to package and query for this information was still being debated by the FHIR spec creators.

You might be able to get a better understanding of how the data was nested by looking at this class: https://github.com/dcarbone/smart-genomics-precision-cancer-medicine/blob/master/SMART%20Genome%20Precision%20Cancer%20Medicine/FHIRDataHelper.m
