### ISSUE TITLE
http://smartgenomics.wikispaces.com/ not available

### ISSUE THREAD

**Issue by songsy** [dcarbone/smart-precision-cancer-medicine#2]
Hi, 

Is there an updated link to http://smartgenomics.wikispaces.com/? It's no longer available. Thanks

**Comment by dcarbone** [comment]
@songsy: sorry, but unfortunately I haven't been involved with this project for a number of years and have not kept up tabs on it.

You can try looking here for more information: https://smarthealthit.org/
